source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

" 窗口最大化
au GUIEnter * simalt ~x
set guioptions-=m        " 隐藏菜单栏
set guioptions-=T        " 隐藏工具栏
set guioptions-=L        " 隐藏左侧滚动条
set guioptions-=r        " 隐藏右侧滚动条
set guioptions-=b        " 隐藏底部滚动条
set guioptions-=0        " 隐藏 tab 栏

set encoding=utf-8       " 编码
set guifont=Consolas:h12 " 字体、字号（linux 下都是在命令行，可不用配置，直接修改命令行样式即可）
set nu                   " 显示行号
set cursorline           " 突出当前行

set tabstop=2            " 设置默认为 2 个空格
set sts=2                " 设置 softtabstop 为 2 个空格，使用 tab 缩进后，删除也是整个 tab 删掉
set expandtab            " 使用空格代替 Tab 键
set shiftwidth=2         " 设置自动缩进 2 个空格（回车缩进 2 个空格）

set nobackup             " 不生成备份文件
set noswapfile           " 不缓存 *.swp 文件
set noundofile           " 不缓存 *.un~ 文件

set foldenable           " 开始折叠
set foldmethod=indent    " 设置语法折叠
set foldcolumn=0         " 设置折叠区域的宽度为 0
setlocal foldlevel=1     " 设置折叠层数为 1
set foldlevelstart=99    " 打开文件是默认不折叠代码

" 用空格键来开关折叠
nnoremap <space> @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')<CR>		

" 窗口切换
nmap <C-h> <C-w><C-h><CR>
nmap <C-j> <C-w><C-j><CR>
nmap <C-k> <C-w><C-k><CR>
nmap <C-l> <C-w><C-l><CR>

" 禁用影响 Gvim 快捷方式的 Windows 快捷方式
unmap <C-v>

" 文件预览器
let mapleader=","
nmap <silent><leader>t :NERDTreeToggle<CR>
autocmd bufenter * if (winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree()) | q | endif

" js 文档
nmap <silent><leader>d <Plug>(jsdoc)

" windows 配色（linux 自带主题）
colorscheme colorsbox-stnight

" windows 透明度（linxu 自带透明）
" http://www.vim.org/scripts/script.php?script_id=687
" 将 dll 文件放至 gvim.eve 同目录即可
au GUIEnter * call libcallnr("vimtweak.dll", "SetAlpha", 184)

" ---------------- 插件 ----------------
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
  " 配色（需要手动复制、启动配色）
  " 复制到 Gvim 安装目录下的 /vimfiles/colors 目录下
  " 在上面引入
  Plugin 'mkarmona/colorsbox' " windows 下需要

  " 文件菜单
  Plugin 'scrooloose/nerdtree'

  " 文件搜索
  Plugin 'kien/ctrlp.vim'

  " 标签补全
  Plugin 'mattn/emmet-vim'

  " 自动补全各种括号、单双引号
  Plugin 'Raimondi/delimitMate'
  
  " 代码对其
  Plugin 'godlygeek/tabular'

  " js 文档
  Plugin 'heavenshell/vim-jsdoc'

  " js 高亮
  Plugin 'pangloss/vim-javascript'

  " es6 高亮
  Plugin 'isRuslan/vim-es6'

  " markdown 高亮
  Plugin 'tpope/vim-markdown'

  " vue 高亮
  Plugin 'posva/vim-vue'

  " react 高亮
  Plugin 'mxw/vim-jsx'

  " CSS 高亮
  Plugin 'gko/vim-coloresque'

  " CSS3 高亮
  Plugin 'hail2u/vim-css3-syntax'
call vundle#end()
filetype plugin indent on
