source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

" 窗口最大化
au GUIEnter * simalt ~x
set guioptions-=m " 隐藏菜单栏
set guioptions-=T " 隐藏工具栏
set guioptions-=L " 隐藏左侧滚动条
set guioptions-=r " 隐藏右侧滚动条
set guioptions-=b " 隐藏底部滚动条
set guioptions-=0 " 隐藏 tab 栏

set encoding=utf-8 " 编码
set guifont=Consolas:h12 " 字体、字号
set nu " 显示行号
set cursorline " 突出当前行

set tabstop=2 " 设置默认为 2 个空格
set sts=2 " 设置 softtabstop 为 2 个空格，使用 tab 缩进后，删除也是整个 tab 删掉
set expandtab " 使用空格代替 Tab 键
set shiftwidth=2 " 设置自动缩进 2 个空格（回车缩进 2 个空格）

set nobackup " 不生成备份文件
set noswapfile " 不缓存 *.swp 文件
set noundofile " 不缓存 *.un~ 文件

set foldmethod=indent " 设置折叠模式

" 文件预览器
let mapleader=","
nmap <silent><leader>t :NERDTreeToggle<CR>
autocmd bufenter * if (winnr('$') == 1 && exists('b:NERDTree')
&& b:NERDTree.isTabTree()) | q | endif

" js 文档
nmap <silent><leader>d <Plug>(jsdoc)

" 修改原来快捷键
nmap <C-Tab> <C-pageUp><CR>
nmap <S-Tab> <C-w><C-w><CR>

" 窗口切换
nmap <C-h> <C-w><C-h><CR>
nmap <C-j> <C-w><C-j><CR>
nmap <C-k> <C-w><C-k><CR>
nmap <C-l> <C-w><C-l><CR>

" 禁用影响 Gvim 快捷方式的 Windows 快捷方式
unmap <C-v>

" ---------------- 插件 ----------------
" 配色
colorscheme colorsbox-stnight

" 透明度
" http://www.vim.org/scripts/script.php?script_id=687
" 将 dll 文件放至 gvim.eve 同目录即可
au GUIEnter * call libcallnr("vimtweak.dll", "SetAlpha", 184)

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
  " 管理工具
  " 需要手动 git clone 到 ~/.vim/bundle/ 目录下
  " Plugin 'VundleVim/Vundle.vim'

  " 配色（需要手动复制、启动配色）
  " 复制到 Gvim 安装目录下的 /vimfiles/colors 目录下
  " 在上面引入
  Plugin 'mkarmona/colorsbox'

  " 文件菜单
  Plugin 'scrooloose/nerdtree'

  " 文件搜索
  Plugin 'kien/ctrlp.vim'

  " 标签补全
  Plugin 'mattn/emmet-vim'

  " 自动补全各种括号、单双引号
  Plugin 'Raimondi/delimitMate'

  " js 文档
  Plugin 'heavenshell/vim-jsdoc'

  " js 高亮
  Plugin 'pangloss/vim-javascript'

  " es6 高亮
  Plugin 'isRuslan/vim-es6'

  " markdown 高亮
  Plugin 'tpope/vim-markdown'

  " vue 高亮
  Plugin 'posva/vim-vue'

  " react 高亮
  Plugin 'mxw/vim-jsx'

  " CSS 高亮
  Plugin 'gko/vim-coloresque'

  " CSS3 高亮
  Plugin 'hail2u/vim-css3-syntax'
call vundle#end()
filetype plugin indent on
